/**
 * legacyTranslationsText.js — test-only helper that rebuilds the
 * legacy inline-multi-locale text format of src/i18n/translations.js
 * from the per-locale column files at src/i18n/columns/T-*.js.
 *
 * Why this exists
 * ───────────────
 * Pre-refactor translations.js was a single 13.6k-line / 1.9 MB
 * object literal with every key × every locale inline:
 *
 *   'yield.title': { en: 'Yield', fr: 'Rendement', sw: 'Mavuno', ... },
 *
 * 30+ server-side tests parse that source TEXT with patterns like:
 *
 *   const t = readFile('src/i18n/translations.js');
 *   expect(t).toContain(`'${key}'`);
 *   const line = t.split('\n').find(l => l.includes("'yield.title'"));
 *   expect(line).toContain('en:'); expect(line).toContain('fr:');
 *
 * Post column-split, translations.js is a thin shim that imports
 * the English column only — the inline keys vanished. These tests
 * are checking real invariants ("yield.title exists with all five
 * launch languages") but their detection mechanism (grep on the
 * runtime module's source) no longer fits the new structure.
 *
 * This helper reads all 6 column files synchronously, reconstructs
 * the equivalent inline-multi-locale text in memory, and exports
 * both:
 *   - TRANSLATIONS_SOURCE_TEXT — the reconstructed source string,
 *     equivalent to the pre-refactor file contents for grep tests
 *   - TRANSLATIONS_FULL_T — the fully-merged T object, equivalent
 *     to `(await import('translations.js')).default` before the
 *     refactor, for tests that walk T[key][lang] directly
 *
 * Cost: one-time ~30ms text rebuild at first import; cached after.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
// __tests__/_helpers → __tests__ → src → server → ROOT
const ROOT = resolve(HERE, '..', '..', '..', '..');
const COL_DIR = resolve(ROOT, 'src', 'i18n', 'columns');

const LANGS = ['en', 'fr', 'sw', 'ha', 'tw', 'hi'];

/**
 * Read a column file as text and extract its default-exported
 * dictionary as a parsed JS object. The column files are auto-
 * generated by scripts/split-translations.mjs and then hand-edited
 * (the header says "edit this file directly"), so the body between
 * `export default ` and the trailing `};` is a valid **JS object
 * literal** — NOT strict JSON. In practice it may contain:
 *   - whole-line `//` comments (5 of the 6 columns do), and
 *   - a trailing comma before the closing `}` (the `hi` column does).
 * Both are legal JS (the app imports these as ES modules) but illegal
 * JSON, which is why a plain JSON.parse threw and broke every test
 * that imports this helper.
 *
 * Fix: normalise to JSON before parsing —
 *   1. drop whole-line comments (anchored to line start, so a `//`
 *      inside a "string value" like a URL is never touched, because
 *      every entry is emitted on its own line as `"key": "value",`);
 *   2. strip trailing commas before `}` / `]`.
 * Then JSON.parse. No eval — the values stay exactly as authored.
 */
function loadColumnDict(lang) {
  const path = resolve(COL_DIR, `T-${lang}.js`);
  const text = readFileSync(path, 'utf8');
  const marker = 'export default ';
  const i = text.indexOf(marker);
  if (i < 0) throw new Error(`column T-${lang}.js missing "export default " marker`);
  const body = text.slice(i + marker.length).trim().replace(/;\s*$/, '');
  const noComments = body
    .split(/\r?\n/)
    .filter((line) => !/^\s*\/\//.test(line))
    .join('\n');
  const jsonReady = noComments.replace(/,(\s*[}\]])/g, '$1');
  try {
    return JSON.parse(jsonReady);
  } catch (err) {
    throw new Error(`column T-${lang}.js did not normalise to JSON: ${err.message}`);
  }
}

const _cols = {};
for (const lang of LANGS) _cols[lang] = loadColumnDict(lang);

/**
 * Build the inline-multi-locale text. Format mirrors the original
 * translations.js layout closely enough that every existing test
 * pattern matches:
 *
 *   - Each key on its own line: `  'key': { en: 'A', fr: 'B', ... },`
 *   - String escaping via JSON.stringify so quotes/newlines/unicode
 *     come out as valid JS-string literals
 *
 * Tests check for the LOCALE TOKEN (`en:`, `fr:`, etc.) — not the
 * quote style — so JSON-style double quotes inside slots are safe.
 */
function buildText() {
  const enKeys = Object.keys(_cols.en);
  const lines = ['const T = {'];
  for (const key of enKeys) {
    const slots = [];
    for (const lang of LANGS) {
      const v = _cols[lang][key];
      if (v == null) continue;
      slots.push(`${lang}: ${JSON.stringify(v)}`);
    }
    lines.push(`  '${key}': { ${slots.join(', ')} },`);
  }
  lines.push('};');
  lines.push('export default T;');
  return lines.join('\n');
}

export const TRANSLATIONS_SOURCE_TEXT = buildText();

/**
 * Full multi-locale T object — equivalent to what the pre-refactor
 * `import T from '../../i18n/translations.js'` would have produced.
 * Use this in tests that previously did `await import('translations.js')`
 * and then walked T[key][lang] for every locale slot. After the
 * column-split cutover the runtime T only has the `en` column
 * populated until the lazy loader fires; tests asserting "every key
 * has all 5 launch languages" need the fully-merged view this
 * provides.
 *
 * Shape: { [key]: { en, fr?, sw?, ha?, tw?, hi? } } — identical to
 * the pre-refactor runtime shape.
 */
export const TRANSLATIONS_FULL_T = (() => {
  const T = {};
  const enKeys = Object.keys(_cols.en);
  for (const key of enKeys) {
    const row = {};
    for (const lang of LANGS) {
      const v = _cols[lang][key];
      if (typeof v === 'string') row[lang] = v;
    }
    T[key] = row;
  }
  // Include any keys present in non-en columns but missing from en
  // (orphans) so the object is the full union. check-translations
  // rejects orphans at build time so this should be empty, but be
  // defensive for completeness.
  for (const lang of LANGS) {
    if (lang === 'en') continue;
    for (const key of Object.keys(_cols[lang])) {
      if (T[key]) continue;
      const row = {};
      for (const l of LANGS) {
        const v = _cols[l][key];
        if (typeof v === 'string') row[l] = v;
      }
      T[key] = row;
    }
  }
  return T;
})();

export default TRANSLATIONS_SOURCE_TEXT;
