/**
 * cropRegistry.test.js — locks the Crop Intelligence Layer contract.
 *
 * Covers the 12 spec tests from the Crop Intelligence Layer brief:
 *
 *   1.  normalizeCropKey handles aliases correctly
 *   2.  getCropLabel returns localized labels
 *   3.  getCropImage returns correct image or fallback
 *   4.  crop stage options change correctly by crop
 *   5.  cassava lifecycle renders properly
 *   6.  maize lifecycle renders properly
 *   7.  stage-specific tasks are generated by selected crop/stage
 *   8.  crop-specific risk patterns are returned safely
 *   9.  yield engine consumes crop profile correctly
 *   10. old crop values normalize safely
 *   11. missing crop definitions do not crash the UI
 *   12. language switching updates crop/stage labels
 *
 * The registry is additive. All existing consumers (riskEngine,
 * yieldEngine, FarmForm, cropStages) keep working with their old
 * inputs — this suite guarantees the NEW surface is well-behaved.
 */

import { describe, it, expect } from 'vitest';

import {
  getCrop,
  getCropLabel,
  getCropImage,
  getCropLifecycle,
  getCropStageLabel,
  getCropRiskPatterns,
  matchCropRiskPatterns,
  getCropSeasonalGuidance,
  getCropCategory,
  normalizeCropKey,
  isCanonicalCropKey,
  listRegisteredCrops,
  CANONICAL_KEYS,
} from '../../../src/config/crops/index.js';
import { getCropStageTasks } from '../../../src/config/crops/cropTaskTemplates.js';
import { getStagesForCrop, STAGES } from '../../../src/utils/cropStages.js';
import { estimateYield } from '../../../src/lib/intelligence/yieldEngine.js';
import { getRisk } from '../../../src/lib/risk/riskEngine.js';

// ─── 1. normalizeCropKey handles aliases correctly ──────────────
describe('normalizeCropKey', () => {
  it('resolves canonical lowercase keys unchanged', () => {
    expect(normalizeCropKey('maize')).toBe('maize');
    expect(normalizeCropKey('cassava')).toBe('cassava');
    expect(normalizeCropKey('rice')).toBe('rice');
  });

  it('folds uppercase and separators', () => {
    expect(normalizeCropKey('MAIZE')).toBe('maize');
    expect(normalizeCropKey('Sweet Potato')).toBe('sweet-potato');
    expect(normalizeCropKey('SWEET_POTATO')).toBe('sweet-potato');
    expect(normalizeCropKey('  Oil Palm  ')).toBe('oil-palm');
  });

  it('maps synonyms to the canonical key', () => {
    expect(normalizeCropKey('corn')).toBe('maize');
    expect(normalizeCropKey('chili')).toBe('pepper');
    expect(normalizeCropKey('chilli')).toBe('pepper');
    expect(normalizeCropKey('garden egg')).toBe('eggplant');
    expect(normalizeCropKey('aubergine')).toBe('eggplant');
    expect(normalizeCropKey('peanut')).toBe('groundnut');
    expect(normalizeCropKey('cacao')).toBe('cocoa');
  });

  it('returns null for empty or unknown inputs', () => {
    expect(normalizeCropKey(null)).toBeNull();
    expect(normalizeCropKey(undefined)).toBeNull();
    expect(normalizeCropKey('')).toBeNull();
    expect(normalizeCropKey('unobtainium')).toBeNull();
  });

  it('collapses structured "OTHER:" values to `other`', () => {
    expect(normalizeCropKey('OTHER:Teff')).toBe('other');
    expect(normalizeCropKey('other:Fonio')).toBe('other');
  });

  it('listRegisteredCrops matches CANONICAL_KEYS', () => {
    expect(listRegisteredCrops()).toBe(CANONICAL_KEYS);
    expect(isCanonicalCropKey('maize')).toBe(true);
    expect(isCanonicalCropKey('made-up-crop')).toBe(false);
  });
});

// ─── 2. getCropLabel returns localized labels ───────────────────
describe('getCropLabel', () => {
  it('returns English label by default', () => {
    expect(getCropLabel('maize')).toMatch(/maize/i);
    expect(getCropLabel('cassava')).toBe('Cassava');
  });

  it('accepts uppercase / synonym inputs', () => {
    expect(getCropLabel('MAIZE')).toMatch(/maize/i);
    expect(getCropLabel('corn')).toMatch(/maize/i);
  });

  it('returns localized labels across supported languages', () => {
    // French, Swahili, Hindi all have cassava translations.
    expect(getCropLabel('cassava', 'fr')).toBe('Manioc');
    expect(getCropLabel('cassava', 'sw')).toBe('Muhogo');
    const hi = getCropLabel('cassava', 'hi');
    expect(hi).toBeTruthy();
    expect(hi).not.toBe('Cassava');    // proves it IS localised
  });

  it('falls back to English for unsupported languages', () => {
    expect(getCropLabel('maize', 'xx')).toMatch(/maize/i);
  });

  it('never returns an empty string for a known crop', () => {
    for (const key of ['cassava', 'maize', 'rice', 'tomato', 'onion']) {
      expect(getCropLabel(key).length).toBeGreaterThan(0);
    }
  });
});

// ─── 3. getCropImage returns correct image or fallback ──────────
describe('getCropImage', () => {
  it('returns the mapped WebP for known crops', () => {
    expect(getCropImage('maize')).toBe('/crops/maize.webp');
    expect(getCropImage('cassava')).toBe('/crops/cassava.webp');
    expect(getCropImage('sweet-potato')).toBe('/crops/sweet-potato.webp');
  });

  it('returns the fallback WebP for unknown or null inputs', () => {
    expect(getCropImage('dragonfruit')).toBe('/crops/fallback-crop.webp');
    expect(getCropImage(null)).toBe('/crops/fallback-crop.webp');
    expect(getCropImage('')).toBe('/crops/fallback-crop.webp');
  });

  it('is always a non-empty string (safe for <img src>)', () => {
    for (const v of [null, undefined, '', 'maize', 'gibberish', 'Oil Palm']) {
      const src = getCropImage(v);
      expect(typeof src).toBe('string');
      expect(src.length).toBeGreaterThan(0);
    }
  });
});

// ─── 4. Crop stage options change correctly by crop ─────────────
describe('getStagesForCrop', () => {
  it('returns cassava-specific stages for cassava', () => {
    const stages = getStagesForCrop('cassava').map((s) => s.value);
    expect(stages).toContain('bulking');
    expect(stages).toContain('maturation');
    expect(stages).toContain('harvest');
  });

  it('returns maize-specific stages for maize', () => {
    const stages = getStagesForCrop('maize').map((s) => s.value);
    expect(stages).toContain('tasseling');
    expect(stages).toContain('grain_fill');
    expect(stages).toContain('harvest');
  });

  it('returns tomato-specific stages for tomato', () => {
    const stages = getStagesForCrop('tomato').map((s) => s.value);
    expect(stages).toContain('flowering');
    expect(stages).toContain('fruiting');
    expect(stages).not.toContain('tasseling');
  });

  it('falls back to the generic list for unknown/empty input', () => {
    const generic = STAGES.map((s) => s.value);
    const resolved = getStagesForCrop('').map((s) => s.value);
    expect(resolved).toEqual(generic);
  });

  it('every decorated stage has an icon and labelKey', () => {
    for (const crop of ['cassava', 'maize', 'tomato']) {
      for (const s of getStagesForCrop(crop)) {
        expect(s.value).toBeTruthy();
        expect(s.icon).toBeTruthy();
        expect(s.labelKey.startsWith('cropStage.')).toBe(true);
      }
    }
  });
});

// ─── 5. Cassava lifecycle renders properly ──────────────────────
describe('cassava lifecycle', () => {
  it('has the expected stage sequence', () => {
    const stages = getCropLifecycle('cassava').map((s) => s.key);
    expect(stages).toEqual([
      'planting', 'establishment', 'vegetative',
      'bulking', 'maturation', 'harvest',
    ]);
  });

  it('each stage has a conservative durationDays', () => {
    for (const stage of getCropLifecycle('cassava')) {
      expect(stage.durationDays).toBeGreaterThan(0);
      expect(stage.durationDays).toBeLessThan(200);
    }
  });
});

// ─── 6. Maize lifecycle renders properly ────────────────────────
describe('maize lifecycle', () => {
  it('has the expected stage sequence', () => {
    const stages = getCropLifecycle('maize').map((s) => s.key);
    expect(stages).toEqual([
      'planting', 'germination', 'vegetative',
      'tasseling', 'grain_fill', 'harvest',
    ]);
  });
});

// ─── 7. Stage-specific tasks by crop/stage ──────────────────────
describe('crop task templates', () => {
  it('returns cassava+planting tasks when asked', () => {
    const tasks = getCropStageTasks('cassava', 'planting');
    expect(tasks.length).toBeGreaterThan(0);
    const titles = tasks.map((t) => t.title.toLowerCase());
    expect(titles.some((t) => /ridge|mound/.test(t))).toBe(true);
    expect(titles.some((t) => /cutting/.test(t))).toBe(true);
  });

  it('returns maize+tasseling tasks that mention water/moisture', () => {
    const tasks = getCropStageTasks('maize', 'tasseling');
    expect(tasks.length).toBeGreaterThan(0);
    const texts = tasks.map((t) => `${t.title} ${t.description}`.toLowerCase());
    expect(texts.some((tt) => /moisture|irrigat|water/.test(tt))).toBe(true);
  });

  it('returns tomato+flowering tasks that mention pest or watering', () => {
    const tasks = getCropStageTasks('tomato', 'flowering');
    expect(tasks.length).toBeGreaterThan(0);
  });

  it('returns an empty frozen array for unknown crop+stage combos', () => {
    const empty = getCropStageTasks('unobtainium', 'bulking');
    expect(empty).toEqual([]);
    expect(Object.isFrozen(empty)).toBe(true);
  });

  it('every template has id/type/priority/title/description/why', () => {
    const sample = getCropStageTasks('cassava', 'planting');
    for (const task of sample) {
      expect(task.id).toBeTruthy();
      expect(task.type).toBeTruthy();
      expect(['high', 'medium', 'low']).toContain(task.priority);
      expect(task.title).toBeTruthy();
      expect(task.description).toBeTruthy();
      expect(task.why).toBeTruthy();
    }
  });
});

// ─── 8. Crop-specific risk patterns returned safely ─────────────
describe('crop risk patterns', () => {
  it('returns cassava patterns including root rot + mosaic', () => {
    const patterns = getCropRiskPatterns('cassava');
    expect(patterns.length).toBeGreaterThan(0);
    const keys = patterns.map((p) => p.messageKey);
    expect(keys.some((k) => k.includes('mosaic'))).toBe(true);
    expect(keys.some((k) => k.includes('root_rot'))).toBe(true);
  });

  it('matches crop patterns by climate/season/stage', () => {
    const matches = matchCropRiskPatterns({
      canonicalKey: 'cassava', climate: 'tropical', season: 'wet',
    });
    expect(matches.length).toBeGreaterThan(0);
    expect(matches[0].type).toBe('pest');
  });

  it('unknown crops return the generic fallback pattern set', () => {
    const patterns = getCropRiskPatterns('unobtainium');
    expect(patterns.length).toBeGreaterThan(0);
  });

  it('risk engine attaches cropPatterns additively', () => {
    const r = getRisk({
      crop: 'cassava',
      regionProfile: { climate: 'tropical', season: 'wet' },
    });
    // Existing contract preserved:
    expect(r.level).toBe('high');
    expect(r.type).toBe('pest');
    expect(r.messageKey).toBeTruthy();
    expect(Array.isArray(r.reasons)).toBe(true);
    // New field:
    expect(Array.isArray(r.cropPatterns)).toBe(true);
    expect(r.cropPatterns.length).toBeGreaterThan(0);
    expect(r.crop).toBe('cassava');
  });

  it('risk engine returns empty cropPatterns when no region profile', () => {
    const r = getRisk({ crop: 'maize' });
    expect(r.cropPatterns).toEqual([]);
  });
});

// ─── 9. Yield engine consumes crop profile correctly ────────────
describe('yield engine integration', () => {
  it('returns a yield range for a known crop + area', () => {
    const est = estimateYield({
      crop: 'maize',
      normalizedAreaSqm: 1000,
      farmType: 'small_farm',
      cropStage: 'vegetative',
    });
    expect(est).not.toBeNull();
    expect(est.lowEstimateKg).toBeGreaterThan(0);
    expect(est.highEstimateKg).toBeGreaterThanOrEqual(est.lowEstimateKg);
    expect(est.unit).toBe('kg');
  });

  it('registry yieldProfile returns null for unknown crops', () => {
    const def = getCrop('unobtainium');
    expect(def).toBeNull(); // unknown crop → null crop definition
  });

  it('registry yieldProfile returns numeric range for known crop', () => {
    const def = getCrop('maize');
    expect(def).not.toBeNull();
    // Maize should have a catalogued yield profile
    if (def.yieldProfile) {
      expect(def.yieldProfile.lowYieldPerSqm).toBeGreaterThan(0);
      expect(def.yieldProfile.unit).toBe('kg/m²');
    }
  });
});

// ─── 10. Old crop values normalize safely ───────────────────────
describe('backward compatibility for old crop values', () => {
  it('legacy English labels resolve to canonical keys', () => {
    // Old farms sometimes stored the display label ("Cassava") instead
    // of the code. The registry collapses them back.
    expect(normalizeCropKey('Cassava')).toBe('cassava');
    expect(normalizeCropKey('Maize')).toBe('maize');
  });

  it('underscored storage codes resolve', () => {
    expect(normalizeCropKey('sweet_potato')).toBe('sweet-potato');
    expect(normalizeCropKey('oil_palm')).toBe('oil-palm');
  });

  it('hyphenated display strings resolve', () => {
    expect(normalizeCropKey('sweet-potato')).toBe('sweet-potato');
    expect(normalizeCropKey('Oil-Palm')).toBe('oil-palm');
  });

  it('getCrop handles every priority crop in CANONICAL_KEYS', () => {
    for (const key of ['cassava', 'maize', 'rice', 'tomato', 'onion',
                        'okra', 'pepper', 'potato', 'banana',
                        'plantain', 'cocoa', 'mango']) {
      const def = getCrop(key);
      expect(def, `${key} should resolve to a definition`).not.toBeNull();
      expect(def.key).toBe(key);
      expect(def.lifecycle.length).toBeGreaterThan(0);
    }
  });
});

// ─── 11. Missing crop definitions do not crash UI ───────────────
describe('graceful fallback for missing crops', () => {
  it('getCrop returns null (not throw) for unknown inputs', () => {
    expect(() => getCrop(null)).not.toThrow();
    expect(() => getCrop('')).not.toThrow();
    expect(() => getCrop('unobtainium')).not.toThrow();
    expect(getCrop('unobtainium')).toBeNull();
  });

  it('getCropLifecycle always returns a non-empty frozen array', () => {
    const unknown = getCropLifecycle('unobtainium');
    expect(Array.isArray(unknown)).toBe(true);
    expect(unknown.length).toBeGreaterThan(0);
  });

  it('getCropStageLabel never returns empty for a known stage', () => {
    expect(getCropStageLabel('maize', 'tasseling')).toBeTruthy();
    expect(getCropStageLabel('maize', 'grain_fill')).toBe('Grain fill');
  });

  it('getCropSeasonalGuidance returns null (not throws) for unknowns', () => {
    expect(getCropSeasonalGuidance('unobtainium')).toBeNull();
    expect(getCropSeasonalGuidance(null)).toBeNull();
  });

  it('getCropCategory returns null for unknowns', () => {
    expect(getCropCategory('unobtainium')).toBeNull();
    expect(getCropCategory(null)).toBeNull();
    expect(getCropCategory('maize')).toBe('grain');
    expect(getCropCategory('cassava')).toBe('root');
    expect(getCropCategory('cocoa')).toBe('cash_crop');
  });
});

// ─── 12. Language switching updates crop/stage labels ───────────
describe('language switching', () => {
  it('crop labels change with language', () => {
    const en = getCropLabel('cassava', 'en');
    const fr = getCropLabel('cassava', 'fr');
    const sw = getCropLabel('cassava', 'sw');
    expect(en).not.toBe(fr);
    expect(en).not.toBe(sw);
    expect(fr).not.toBe(sw);
  });

  it('stage labels humanise consistently (English-first)', () => {
    // Full i18n for stage names lives in the translation system;
    // getCropStageLabel returns a safe humanised fallback so the UI
    // never renders a snake_case key when the translation is missing.
    expect(getCropStageLabel('maize', 'grain_fill')).toBe('Grain fill');
    expect(getCropStageLabel('cassava', 'bulking')).toBe('Bulking');
    expect(getCropStageLabel('tomato', 'fruiting')).toBe('Fruiting');
  });

  it('unknown stage keys fall through without throwing', () => {
    expect(() => getCropStageLabel('cassava', 'unobtainable_stage')).not.toThrow();
    expect(getCropStageLabel('cassava', 'unobtainable_stage')).toBeTruthy();
  });
});

// ─── Registry shape contract ────────────────────────────────────
describe('getCrop — composed shape', () => {
  it('returns the full contract for maize', () => {
    const def = getCrop('maize');
    expect(def).toBeTruthy();
    expect(def.key).toBe('maize');
    expect(def.labels.en).toMatch(/maize/i);
    expect(def.image).toMatch(/\/crops\/maize\.webp$/);
    expect(def.category).toBe('grain');
    expect(def.lifecycle.length).toBeGreaterThan(0);
    expect(def.defaultTaskTemplates.planting).toBeDefined();
    expect(Array.isArray(def.riskPatterns)).toBe(true);
    expect(def.seasonalGuidance.plantingWindow).toBeTruthy();
  });

  it('returns the full contract for cassava', () => {
    const def = getCrop('cassava');
    expect(def.key).toBe('cassava');
    expect(def.category).toBe('root');
    expect(def.lifecycle.map((s) => s.key)).toContain('bulking');
    expect(def.defaultTaskTemplates.bulking).toBeDefined();
  });

  it('labels map contains at least en/fr/sw/hi for priority crops', () => {
    const def = getCrop('maize');
    for (const lang of ['en', 'fr', 'sw', 'hi']) {
      expect(def.labels[lang]).toBeTruthy();
    }
  });
});
