/**
 * cropImages.js — centralised catalog mapping canonical crop keys
 * to optimised WebP image paths under /public/crops.
 *
 *   getCropImagePath('maize')   → '/crops/maize.webp'
 *   getCropImagePath('MAIZE')   → '/crops/maize.webp'   // case-insensitive
 *   getCropImagePath('unknown') → null                  // caller shows placeholder
 *
 *   hasCropImage(key) → boolean
 *
 * Principles
 *   • lowercase canonical keys so the same mapping works for the
 *     modern uppercase storage shape (`MAIZE`) and legacy lowercase
 *     (`maize`) — we only ever normalise, never rename.
 *   • The mapping is a frozen object literal so it's fast to look up
 *     and can't be mutated by callers.
 *   • Missing entries return `null` — the CropImage component turns
 *     that into the generic `/crops/_placeholder.svg` fallback. No
 *     crashes, no broken `<img>` tags.
 *
 * Adding a new crop image
 *   1. Drop `<key>.webp` into /public/crops (keep it square, ≤80kb).
 *   2. Add a row to CROP_IMAGE_PATHS below:
 *        newcrop: '/crops/newcrop.webp',
 *   3. That's it — every CropImage consumer picks it up on next
 *      render. No other code touches image paths directly.
 */

import { normalizeCrop } from './crops.js';

// Fallback used when a crop has no catalog mapping OR the mapped
// asset 404s at runtime. The .webp is shipped alongside the rest
// in /public/crops — same style, same palette, generic sprout +
// soil mound so the UI never shows a broken image icon.
export const CROP_IMAGE_PLACEHOLDER = '/crops/fallback-crop.webp';

// Generic placeholder served from the new /images/placeholders
// folder — used when even the legacy fallback is unavailable.
// SVG keeps the asset weight at <2 KB and renders crisply at any
// size without an extra request per crop.
export const CROP_IMAGE_PLACEHOLDER_SVG = '/images/placeholders/crop.svg';

/**
 * V2 path table — production-photo slots under /public/images/crops.
 * These rows map to curated real-photo WebP files (16 priority crops
 * for the pilot). When the file is not yet on disk, the runtime
 * fallback chain in `getCropImagePath` will degrade to the legacy
 * /crops/*.webp illustrations and finally to the SVG placeholder.
 *
 * Adding a new slot: drop the .webp into /public/images/crops with
 * the exact filename below, then this row resolves automatically.
 */
export const CROP_IMAGE_PATHS_V2 = Object.freeze({
  tomato:         '/images/crops/tomato.webp',
  maize:          '/images/crops/maize.webp',
  pepper:         '/images/crops/pepper.webp',
  cassava:        '/images/crops/cassava.webp',
  onion:          '/images/crops/onion.webp',
  'leafy-greens': '/images/crops/leafy-greens.webp',
  leafy_greens:   '/images/crops/leafy-greens.webp',
  leafygreens:    '/images/crops/leafy-greens.webp',
  okra:           '/images/crops/okra.webp',
  rice:           '/images/crops/rice.webp',
  yam:            '/images/crops/yam.webp',
  plantain:       '/images/crops/plantain.webp',
  beans:          '/images/crops/beans.webp',
  potato:         '/images/crops/potato.webp',
  carrot:         '/images/crops/carrot.webp',
  basil:          '/images/crops/basil.webp',
  spinach:        '/images/crops/spinach.webp',
  herbs:          '/images/crops/herbs.webp',
});

/**
 * Tracks which V2 photo files have actually shipped under
 * /public/images/crops. Empty by default — populate as curated
 * photos are committed. Until a key is in this set, callers that
 * want photo-only resolution can branch on `hasRealCropPhoto`.
 */
export const AVAILABLE_CROP_PHOTOS_V2 = Object.freeze(new Set([
  // Real-photo files land here as they're sourced + committed.
]));

/**
 * Canonical lowercase crop key → image path. Keys match the codes in
 * src/config/crops.js (normalised to lowercase) so the mapping is
 * consistent across yield ranges, prices, and this image catalog.
 *
 * The full list intentionally mirrors the crops we already price +
 * range. Adding a new row here without an actual file will just
 * render the placeholder (tested in cropImage.test.js), so entries
 * can land slightly ahead of the asset drop.
 */
// Canonical crop → WebP image path. 16 crops ship real WebP assets
// under /public/crops today (3–5 KB each, generated by
// scripts/gen-crop-images.mjs — consistent dark radial gradient
// + detailed crop illustration with gradients / highlights / contact
// shadow). Rows pointing at not-yet-shipped .webp files fall back
// to /crops/fallback-crop.webp via the onError handler.
export const CROP_IMAGE_PATHS = Object.freeze({
  // Staples + grains
  maize:          '/crops/maize.webp',
  corn:           '/crops/maize.webp',        // synonym
  rice:           '/crops/rice.webp',
  wheat:          '/crops/wheat.webp',
  sorghum:        '/crops/sorghum.webp',
  millet:         '/crops/millet.webp',
  barley:         '/crops/barley.webp',
  // Roots + tubers
  cassava:        '/crops/cassava.webp',
  yam:            '/crops/yam.webp',
  potato:         '/crops/potato.webp',
  'sweet-potato': '/crops/sweet-potato.webp',
  sweet_potato:   '/crops/sweet-potato.webp',  // underscore variant
  sweetpotato:    '/crops/sweet-potato.webp',  // no-separator variant
  // Legumes
  beans:          '/crops/beans.webp',
  bean:           '/crops/beans.webp',
  soybean:        '/crops/soybean.webp',
  groundnut:      '/crops/groundnut.webp',
  peanut:         '/crops/groundnut.webp',
  cowpea:         '/crops/cowpea.webp',
  chickpea:       '/crops/chickpea.webp',
  lentil:         '/crops/lentil.webp',
  // Vegetables
  tomato:         '/crops/tomato.webp',
  onion:          '/crops/onion.webp',
  pepper:         '/crops/pepper.webp',
  chili:          '/crops/pepper.webp',
  cabbage:        '/crops/cabbage.webp',
  carrot:         '/crops/carrot.webp',
  okra:           '/crops/okra.webp',
  cucumber:       '/crops/cucumber.webp',
  watermelon:     '/crops/watermelon.webp',
  eggplant:       '/crops/eggplant.webp',
  aubergine:      '/crops/eggplant.webp',   // UK synonym
  garlic:         '/crops/garlic.webp',
  ginger:         '/crops/ginger.webp',
  lettuce:        '/crops/lettuce.webp',
  spinach:        '/crops/spinach.webp',
  // Tree + permanent
  banana:         '/crops/banana.webp',
  plantain:       '/crops/plantain.webp',
  mango:          '/crops/mango.webp',
  avocado:        '/crops/avocado.webp',
  orange:         '/crops/orange.webp',
  coffee:         '/crops/coffee.webp',
  tea:            '/crops/tea.webp',
  cocoa:          '/crops/cocoa.webp',
  cacao:          '/crops/cocoa.webp',        // synonym
  'oil-palm':     '/crops/oil-palm.webp',
  oil_palm:       '/crops/oil-palm.webp',     // underscore variant
  oilpalm:        '/crops/oil-palm.webp',     // no-separator variant
  palm:           '/crops/oil-palm.webp',     // shorthand
  cotton:         '/crops/cotton.webp',
  sugarcane:      '/crops/sugarcane.webp',
  sunflower:      '/crops/sunflower.webp',
  sesame:         '/crops/sesame.webp',
});

/**
 * Tracks which images actually exist in /public/crops at build time.
 * The CropImage component still uses a runtime `onError` fallback,
 * but this set lets us cheaply answer "is the asset expected to
 * resolve?" without a network round-trip — useful for tests.
 *
 * Update this set when you drop a new webp into /public/crops.
 * (The `_placeholder.svg` is always available.)
 */
export const AVAILABLE_CROP_IMAGES = Object.freeze(new Set([
  // Seed with the placeholder only; real images land as they're
  // optimised + committed. An entry listed in CROP_IMAGE_PATHS but
  // missing from this set still renders — the browser falls back via
  // the component's onError handler.
]));

/**
 * getCropImagePath — resolve a crop key to an image URL, or null
 * when the catalog has no mapping. Accepts:
 *   - canonical lowercase  ('maize', 'sweet-potato', 'sweet_potato')
 *   - storage uppercase    ('MAIZE', 'SWEET-POTATO')
 *   - display string       ('Maize', 'Sweet Potato', 'Oil Palm')
 *   - structured "other"   ('OTHER:Teff') → null (use placeholder)
 *
 * Hyphen + underscore + space forms all collapse to the same row:
 *   'sweet-potato' === 'sweet_potato' === 'Sweet Potato' === 'SWEETPOTATO'
 *
 * Returns null when no mapping exists OR when the input is empty.
 * The caller's CropImage component turns `null` into the generic
 * placeholder so the UI never shows a broken image.
 */
export function getCropImagePath(cropKey) {
  const raw = String(cropKey || '').trim().toLowerCase();
  if (!raw) return null;

  // V2 production-photo path takes priority — only resolves when
  // the curated real photo is listed in AVAILABLE_CROP_PHOTOS_V2,
  // so a row in CROP_IMAGE_PATHS_V2 without a shipped file will
  // fall through to the legacy illustration cleanly.
  const v2Hit = _resolveV2Path(raw, cropKey);
  if (v2Hit) return v2Hit;

  // Try the exact lowercase form first (handles 'sweet-potato' /
  // 'oil-palm' / 'sweet_potato' verbatim).
  if (CROP_IMAGE_PATHS[raw]) return CROP_IMAGE_PATHS[raw];

  // Collapse any separator (space / hyphen / underscore) to try both
  // canonical shapes without listing every permutation in the table.
  const hyphenated  = raw.replace(/[\s_]+/g, '-');
  if (CROP_IMAGE_PATHS[hyphenated]) return CROP_IMAGE_PATHS[hyphenated];
  const underscored = raw.replace(/[\s-]+/g, '_');
  if (CROP_IMAGE_PATHS[underscored]) return CROP_IMAGE_PATHS[underscored];

  // Fall back to the legacy normalizeCrop path (handles uppercase
  // storage codes + OTHER:… structured values).
  const normalised = normalizeCrop(cropKey);
  if (normalised && CROP_IMAGE_PATHS[normalised]) return CROP_IMAGE_PATHS[normalised];

  return null;
}

/**
 * Internal: resolves a V2 photo path only when the asset is known
 * to ship in the AVAILABLE_CROP_PHOTOS_V2 set. Pure function — no
 * network calls. The runtime onError fallback in <CropImage /> is
 * the second line of defence if the set drifts from disk reality.
 */
function _resolveV2Path(rawLower, originalKey) {
  if (!rawLower || AVAILABLE_CROP_PHOTOS_V2.size === 0) return null;
  const variants = new Set([
    rawLower,
    rawLower.replace(/[\s_]+/g, '-'),
    rawLower.replace(/[\s-]+/g, '_'),
  ]);
  const norm = normalizeCrop(originalKey);
  if (norm) variants.add(String(norm).toLowerCase());
  for (const v of variants) {
    if (CROP_IMAGE_PATHS_V2[v] && AVAILABLE_CROP_PHOTOS_V2.has(v)) {
      return CROP_IMAGE_PATHS_V2[v];
    }
  }
  return null;
}

/**
 * hasRealCropPhoto — true when a curated real-photo WebP for this
 * crop key has shipped under /public/images/crops. Useful for UI
 * surfaces that want to A/B branch on "have we got a real photo
 * yet?" without inspecting paths directly.
 */
export function hasRealCropPhoto(cropKey) {
  const raw = String(cropKey || '').trim().toLowerCase();
  if (!raw) return false;
  return _resolveV2Path(raw, cropKey) !== null;
}

/**
 * getCropImage — alias for getCropImagePath that always returns a
 * usable URL. Missing mappings resolve to the placeholder so callers
 * who don't want to branch on null can drop the result straight into
 * an <img src>.
 *
 *   getCropImage('maize')        → '/crops/maize.webp'
 *   getCropImage('dragonfruit')  → '/crops/_placeholder.svg'
 */
export function getCropImage(cropKey) {
  return getCropImagePath(cropKey) || CROP_IMAGE_PLACEHOLDER;
}

/**
 * hasCropImage — quick lookup, useful for tests + analytics. True
 * when a mapping exists in CROP_IMAGE_PATHS (not whether the asset
 * is physically on disk — that's AVAILABLE_CROP_IMAGES).
 */
export function hasCropImage(cropKey) {
  return getCropImagePath(cropKey) !== null;
}

export const _internal = Object.freeze({ CROP_IMAGE_PATHS, AVAILABLE_CROP_IMAGES });
