#!/usr/bin/env node
/**
 * scripts/_add_translation_keys.mjs
 *
 * Add a batch of translation keys to all 6 column files in one
 * atomic operation. Use when migrating hardcoded JSX literals
 * to tSafe() calls — every new key must land in T-en + the four
 * other launch-complete columns (fr/sw/ha/tw) so the
 * check:translations parity gate keeps passing.
 *
 * For non-English columns we ship the SAME ENGLISH STRING as a
 * placeholder. This is intentional: it preserves the pre-refactor
 * runtime behaviour (user already saw English because the JSX was
 * hardcoded English) but moves the string under translation
 * control, so a translator can later edit the per-locale file
 * without code changes. The dev mismatch detector will surface
 * each English-as-placeholder value when a non-en locale is
 * active, giving translators a precise work-list.
 *
 * Hindi: skipped for new English-only keys (T-hi.js has its own
 * 3486-baseline ratchet; adding more English bloats the file and
 * doesn't help Hindi coverage).
 *
 * Usage from another node script:
 *   import { addKeys } from './_add_translation_keys.mjs';
 *   await addKeys({
 *     'home.streakDayCount':       '{n}-day streak',
 *     'home.weatherStatusUpdating': 'Updating…',
 *     'home.weatherStatusLive':     'Live',
 *   });
 *
 * Or from the shell:
 *   echo '{"home.streakDayCount":"{n}-day streak"}' | node scripts/_add_translation_keys.mjs --stdin
 *
 * Idempotent: keys that already exist with the same value are
 * left untouched. Keys that exist with a different value are
 * NOT overwritten — the script logs a warning and skips them so
 * translator-supplied values are never clobbered.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const COL_DIR = resolve(ROOT, 'src', 'i18n', 'columns');

const COLUMNS_TO_BACKFILL = ['en', 'fr', 'sw', 'ha', 'tw'];

async function loadColumn(lang) {
  const p = resolve(COL_DIR, `T-${lang}.js`);
  const mod = await import(pathToFileURL(p).href + `?t=${Date.now()}`);
  return { path: p, dict: mod.default };
}

function serialize(dict, lang, count) {
  return (
    `// AUTO-GENERATED by scripts/split-translations.mjs — do not edit by hand.\n`
    + `// Locale column: ${lang}. ${count} keys.\n`
    + `// To change a translation, edit this file directly and commit.\n`
    + `// To regenerate from a multi-locale source, restore translations.js from git.\n`
    + `\n`
    + `export default ${JSON.stringify(dict, null, 2)};\n`
  );
}

export async function addKeys(newKeys, opts = {}) {
  const langs = opts.langs || COLUMNS_TO_BACKFILL;
  const report = { added: {}, skipped: {}, conflicts: {} };
  for (const lang of langs) {
    const { path, dict } = await loadColumn(lang);
    const updated = { ...dict };
    report.added[lang] = 0;
    report.skipped[lang] = 0;
    report.conflicts[lang] = [];
    for (const [key, value] of Object.entries(newKeys)) {
      if (key in updated) {
        if (updated[key] === value) {
          report.skipped[lang] += 1;
        } else {
          // Existing value differs — don't overwrite. Translator
          // edits win.
          report.conflicts[lang].push({ key, existing: updated[key], proposed: value });
          report.skipped[lang] += 1;
        }
        continue;
      }
      updated[key] = value;
      report.added[lang] += 1;
    }
    writeFileSync(path, serialize(updated, lang, Object.keys(updated).length), 'utf8');
  }
  return report;
}

// CLI entrypoint
if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  const args = process.argv.slice(2);
  const fromStdin = args.includes('--stdin');
  let payload = {};
  if (fromStdin) {
    const chunks = [];
    for await (const c of process.stdin) chunks.push(c);
    payload = JSON.parse(Buffer.concat(chunks).toString('utf8'));
  } else {
    console.error('Usage: echo \'{"key":"value"}\' | node scripts/_add_translation_keys.mjs --stdin');
    process.exit(1);
  }
  const report = await addKeys(payload);
  console.log(JSON.stringify(report, null, 2));
}
