// i18n-scan.mjs — the localization pipeline core (npm run i18n:scan / i18n:missing /
// i18n:coverage). Extracts every tSafe/tStrict key+fallback from src, classifies each
// usage as FARMER-facing or ADMIN/internal by path, and diffs against the canonical
// key set (T-en.js — column parity to the other locales is enforced separately by
// check:translations). This catches the class every parity gate misses: keys used in
// components but registered in NO column (English fallback leaks — the root cause of
// all three 2026-07-01 screenshot batches).
//
//   node scripts/i18n-scan.mjs             → console summary
//   node scripts/i18n-scan.mjs --missing   → list unregistered keys (key ||| fallback)
//   node scripts/i18n-scan.mjs --report    → writes FARMER_TRANSLATION_COVERAGE.md (real numbers)
//   node scripts/i18n-scan.mjs --json      → machine-readable (used by the farmer gate)
import fs from 'node:fs';
import path from 'node:path';

const ADMIN_RE = /admin|internal|ngo|Ngo|NGO|org|Org|founder|Founder|enterprise|buyer|Community|Moderation|Agent|fieldOfficer|FieldOfficer|scanLab|network|command-center|commandCenter\/(?!FarmStatusCard)/;
const RE = /t(?:Safe|Strict)\(\s*'([^']+)'\s*,\s*'((?:[^'\\]|\\.)*)'/g;

export function scan(root = '.') {
  const en = fs.readFileSync(path.join(root, 'src/i18n/columns/T-en.js'), 'utf8');
  const files = [];
  const walk = (d) => {
    for (const f of fs.readdirSync(d)) {
      const p = path.join(d, f); const s = fs.statSync(p);
      if (s.isDirectory()) walk(p);
      else if (/\.(jsx|js|ts|tsx)$/.test(f) && !/\.test\./.test(f)) files.push(p);
    }
  };
  walk(path.join(root, 'src'));
  const usages = { farmer: {}, admin: {} };
  const missing = { farmer: {}, admin: {} };
  const perFile = {};
  for (const f of files) {
    if (f.includes('i18n' + path.sep + 'columns')) continue;
    const src = fs.readFileSync(f, 'utf8');
    const cls = ADMIN_RE.test(f) ? 'admin' : 'farmer';
    for (const m of src.matchAll(RE)) {
      usages[cls][m[1]] = true;
      if (!en.includes('"' + m[1] + '"')) {
        missing[cls][m[1]] = m[2];
        perFile[f] = (perFile[f] || 0) + 1;
      }
    }
  }
  const count = (o) => Object.keys(o).length;
  return {
    scannedFiles: files.length,
    farmer: { used: count(usages.farmer), missing: count(missing.farmer), missingKeys: missing.farmer },
    admin: { used: count(usages.admin), missing: count(missing.admin), missingKeys: missing.admin },
    topFiles: Object.entries(perFile).sort((a, b) => b[1] - a[1]).slice(0, 15),
  };
}

const args = process.argv.slice(2);
const r = scan();
const fCov = r.farmer.used ? Math.round(100 * (r.farmer.used - r.farmer.missing) / r.farmer.used) : 100;
const aCov = r.admin.used ? Math.round(100 * (r.admin.used - r.admin.missing) / r.admin.used) : 100;

if (args.includes('--json')) {
  console.log(JSON.stringify({ farmerUsed: r.farmer.used, farmerMissing: r.farmer.missing,
    adminUsed: r.admin.used, adminMissing: r.admin.missing }));
} else if (args.includes('--missing')) {
  for (const [k, v] of Object.entries(r.farmer.missingKeys)) console.log('[farmer] ' + k + ' ||| ' + v);
  for (const [k, v] of Object.entries(r.admin.missingKeys)) console.log('[admin]  ' + k + ' ||| ' + v);
} else {
  console.log('[i18n:scan] files ' + r.scannedFiles
    + ' | FARMER keys used ' + r.farmer.used + ', unregistered ' + r.farmer.missing + ' (' + fCov + '% registered)'
    + ' | ADMIN keys used ' + r.admin.used + ', unregistered ' + r.admin.missing + ' (' + aCov + '% registered)');
}
if (args.includes('--report')) {
  const lines = [
    '# Farmer Translation Coverage', '',
    '*Generated by `npm run i18n:coverage` — real scan output, regenerate any time. Registered =',
    'key exists in the canonical column set (all launch locales are then 100%-parity-enforced by',
    '`check:translations`). Unregistered = English fallback renders in every locale.*', '',
    '| Class | Keys used | Unregistered | Registered % |', '|---|---|---|---|',
    '| **Farmer-facing** | ' + r.farmer.used + ' | ' + r.farmer.missing + ' | **' + fCov + '%** |',
    '| Admin/internal (tracked, deprioritized) | ' + r.admin.used + ' | ' + r.admin.missing + ' | ' + aCov + '% |',
    '', '## Top files by unregistered keys',
    ...r.topFiles.map(([f, n]) => '- `' + f.replace(/\\/g, '/') + '` — ' + n),
    '', 'The farmer-facing count is RATCHETED by `check:i18n-farmer-gate` (build:safe): it may only',
    'fall. Fix flow: `npm run i18n:missing` → translate the batch (see scripts/fix-leaks-batch*.mjs',
    'pattern) → `node scripts/fill-language-parity.mjs` → gate tightens automatically.',
  ];
  fs.writeFileSync('FARMER_TRANSLATION_COVERAGE.md', lines.join('\n') + '\n');
  console.log('[i18n:scan] wrote FARMER_TRANSLATION_COVERAGE.md');
}
