import prisma from '../../config/database.js';
import { getRegionConfig, DEFAULT_COUNTRY_CODE } from '../regionConfig/service.js';

/**
 * Reminder Service
 * Rule-based, crop/region-aware reminder system.
 * Reminders can be auto-generated (from activities) or manually created.
 *
 * Schema uses: completed (Boolean), completedAt (DateTime?)
 */

const VALID_REMINDER_TYPES = [
  'fertilizing', 'weeding', 'spraying', 'irrigation', 'harvesting',
  'storage_check', 'market_check', 'pest_inspection', 'drying_reminder',
  'harvest_check', 'farm_visit_followup', 'evidence_completion', 'general', 'custom',
];

export async function createReminder(farmerId, data) {
  const farmer = await prisma.farmer.findUnique({ where: { id: farmerId } });
  if (!farmer) {
    const err = new Error('Farmer not found');
    err.statusCode = 404;
    throw err;
  }

  // Validate reminderType
  const reminderType = data.reminderType || 'custom';
  if (!VALID_REMINDER_TYPES.includes(reminderType)) {
    const err = new Error(`Invalid reminderType. Must be one of: ${VALID_REMINDER_TYPES.join(', ')}`);
    err.statusCode = 400;
    throw err;
  }

  // Validate dueDate is a valid date
  const dueDate = new Date(data.dueDate);
  if (isNaN(dueDate.getTime())) {
    const err = new Error('Invalid dueDate — must be a valid date string');
    err.statusCode = 400;
    throw err;
  }

  return prisma.reminder.create({
    data: {
      farmerId,
      reminderType,
      title: data.title,
      message: data.message,
      dueDate,
      metadata: data.metadata || null,
    },
  });
}

export async function listReminders(farmerId, filters = {}) {
  const where = { farmerId };

  if (filters.status === 'pending') {
    where.completed = false;
  } else if (filters.status === 'done') {
    where.completed = true;
  }

  if (filters.type) where.reminderType = filters.type;

  // Filter overdue
  if (filters.overdue === 'true') {
    where.completed = false;
    where.dueDate = { lt: new Date() };
  }

  return prisma.reminder.findMany({
    where,
    orderBy: { dueDate: 'asc' },
    include: { farmer: { select: { id: true, fullName: true } } },
  });
}

export async function markDone(id) {
  const reminder = await prisma.reminder.findUnique({ where: { id } });
  if (!reminder) {
    const err = new Error('Reminder not found');
    err.statusCode = 404;
    throw err;
  }
  return prisma.reminder.update({
    where: { id },
    data: { completed: true, completedAt: new Date() },
  });
}

export async function dismissReminder(id) {
  const reminder = await prisma.reminder.findUnique({ where: { id } });
  if (!reminder) {
    const err = new Error('Reminder not found');
    err.statusCode = 404;
    throw err;
  }
  // Mark completed but add metadata noting it was dismissed
  return prisma.reminder.update({
    where: { id },
    data: {
      completed: true,
      completedAt: new Date(),
      metadata: { ...(reminder.metadata || {}), dismissed: true },
    },
  });
}

export async function getReminderSummary(farmerId) {
  const now = new Date();
  const [pending, overdue, completedThisMonth] = await Promise.all([
    prisma.reminder.count({ where: { farmerId, completed: false } }),
    prisma.reminder.count({ where: { farmerId, completed: false, dueDate: { lt: now } } }),
    prisma.reminder.count({
      where: {
        farmerId, completed: true,
        completedAt: { gte: new Date(now.getFullYear(), now.getMonth(), 1) },
      },
    }),
  ]);

  const upcoming = await prisma.reminder.findMany({
    where: { farmerId, completed: false, dueDate: { gte: now } },
    orderBy: { dueDate: 'asc' },
    take: 5,
  });

  return { pending, overdue, completedThisMonth, upcoming };
}

/**
 * Generate crop lifecycle reminders for a farmer.
 * Called when a farmer registers a new crop/season.
 */
export async function generateCropLifecycleReminders(farmerId, cropType, plantingDate) {
  const farmer = await prisma.farmer.findUnique({ where: { id: farmerId } });
  const regionCfg = getRegionConfig(farmer?.countryCode || DEFAULT_COUNTRY_CODE);

  const schedules = getCropSchedule(cropType);
  const reminders = [];

  for (const step of schedules) {
    const dueDate = addDays(new Date(plantingDate), step.daysAfterPlanting);
    reminders.push({
      farmerId,
      reminderType: step.type,
      title: step.title,
      message: step.message.replace('{crop}', cropType),
      dueDate,
      metadata: { cropType, plantingDate, autoGenerated: true },
    });
  }

  const created = [];
  for (const r of reminders) {
    try {
      created.push(await prisma.reminder.create({ data: r }));
    } catch (e) {
      console.error('Failed to create lifecycle reminder:', e.message);
    }
  }

  return created;
}

// ─── Crop schedule templates ────────────────────────────

function getCropSchedule(cropType) {
  const schedules = {
    maize: [
      { daysAfterPlanting: 14, type: 'fertilizing', title: 'First fertilizer application', message: 'Apply first top-dressing fertilizer to your {crop}.' },
      { daysAfterPlanting: 21, type: 'weeding', title: 'First weeding', message: 'Your {crop} field needs weeding — 3 weeks since planting.' },
      { daysAfterPlanting: 35, type: 'spraying', title: 'Pest check', message: 'Check your {crop} for fall armyworm and other pests.' },
      { daysAfterPlanting: 42, type: 'fertilizing', title: 'Second fertilizer application', message: 'Apply second top-dressing to your {crop}.' },
      { daysAfterPlanting: 90, type: 'harvesting', title: 'Harvest approaching', message: 'Your {crop} may be ready for harvest soon. Check maturity.' },
      { daysAfterPlanting: 100, type: 'storage_check', title: 'Post-harvest storage', message: 'Ensure proper drying and storage for your {crop}.' },
    ],
    wheat: [
      { daysAfterPlanting: 21, type: 'fertilizing', title: 'Top-dressing time', message: 'Apply nitrogen top-dressing to your {crop}.' },
      { daysAfterPlanting: 30, type: 'spraying', title: 'Rust check', message: 'Inspect your {crop} for stem and leaf rust.' },
      { daysAfterPlanting: 60, type: 'spraying', title: 'Disease check', message: 'Check {crop} for diseases — apply fungicide if needed.' },
      { daysAfterPlanting: 120, type: 'harvesting', title: 'Harvest approaching', message: 'Your {crop} should be approaching maturity.' },
    ],
    rice: [
      { daysAfterPlanting: 14, type: 'weeding', title: 'First weeding', message: 'Weed your {crop} paddy — critical in early stage.' },
      { daysAfterPlanting: 30, type: 'fertilizing', title: 'Fertilizer application', message: 'Apply fertilizer to your {crop} paddy.' },
      { daysAfterPlanting: 45, type: 'irrigation', title: 'Water management', message: 'Ensure adequate water levels in your {crop} paddy.' },
      { daysAfterPlanting: 120, type: 'harvesting', title: 'Harvest time', message: 'Your {crop} should be ready for harvest.' },
    ],
    coffee: [
      { daysAfterPlanting: 30, type: 'weeding', title: 'Weed control', message: 'Keep your {crop} plantation weed-free.' },
      { daysAfterPlanting: 60, type: 'spraying', title: 'CBD prevention', message: 'Apply fungicide to prevent coffee berry disease.' },
      { daysAfterPlanting: 90, type: 'fertilizing', title: 'Nutrition boost', message: 'Apply fertilizer to your {crop} trees.' },
    ],
  };

  return schedules[cropType?.toLowerCase()] || [
    { daysAfterPlanting: 14, type: 'weeding', title: 'First weeding', message: 'Check your {crop} field for weeds.' },
    { daysAfterPlanting: 30, type: 'fertilizing', title: 'Fertilizer check', message: 'Consider fertilizer application for your {crop}.' },
    { daysAfterPlanting: 90, type: 'harvesting', title: 'Harvest check', message: 'Check if your {crop} is approaching harvest time.' },
  ];
}

function addDays(date, days) {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result;
}
